version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    groups:
      pytorch:
        applies-to: version-updates
        patterns: [torch, torchvision]
      pytorch-security:
        applies-to: security-updates
        patterns: [torch, torchvision]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
